/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin.route'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicPingRouteImport } from './routes/api/public/ping'
import { Route as AuthenticatedDashboardTransactionsRouteImport } from './routes/_authenticated/dashboard.transactions'
import { Route as AuthenticatedDashboardRefillRouteImport } from './routes/_authenticated/dashboard.refill'
import { Route as AuthenticatedDashboardOrderHistoryRouteImport } from './routes/_authenticated/dashboard.order-history'
import { Route as AuthenticatedDashboardAddFundsRouteImport } from './routes/_authenticated/dashboard.add-funds'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin.services'
import { Route as AuthenticatedAdminProvidersRouteImport } from './routes/_authenticated/admin.providers'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin.logs'
import { Route as ApiPublicHooksTelegramRouteImport } from './routes/api/public/hooks/telegram'
import { Route as ApiPublicHooksStatusSyncRouteImport } from './routes/api/public/hooks/status-sync'
import { Route as ApiPublicHooksRetryFailedOrdersRouteImport } from './routes/api/public/hooks/retry-failed-orders'
import { Route as ApiPublicHooksImportServicesRouteImport } from './routes/api/public/hooks/import-services'
import { Route as ApiPublicHooksCleanLogsRouteImport } from './routes/api/public/hooks/clean-logs'
import { Route as ApiPublicHooksBalanceSyncRouteImport } from './routes/api/public/hooks/balance-sync'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiPublicPingRoute = ApiPublicPingRouteImport.update({
  id: '/api/public/ping',
  path: '/api/public/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardTransactionsRoute =
  AuthenticatedDashboardTransactionsRouteImport.update({
    id: '/dashboard/transactions',
    path: '/dashboard/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRefillRoute =
  AuthenticatedDashboardRefillRouteImport.update({
    id: '/dashboard/refill',
    path: '/dashboard/refill',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardOrderHistoryRoute =
  AuthenticatedDashboardOrderHistoryRouteImport.update({
    id: '/dashboard/order-history',
    path: '/dashboard/order-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAddFundsRoute =
  AuthenticatedDashboardAddFundsRouteImport.update({
    id: '/dashboard/add-funds',
    path: '/dashboard/add-funds',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProvidersRoute =
  AuthenticatedAdminProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiPublicHooksTelegramRoute = ApiPublicHooksTelegramRouteImport.update({
  id: '/api/public/hooks/telegram',
  path: '/api/public/hooks/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksStatusSyncRoute =
  ApiPublicHooksStatusSyncRouteImport.update({
    id: '/api/public/hooks/status-sync',
    path: '/api/public/hooks/status-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRetryFailedOrdersRoute =
  ApiPublicHooksRetryFailedOrdersRouteImport.update({
    id: '/api/public/hooks/retry-failed-orders',
    path: '/api/public/hooks/retry-failed-orders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksImportServicesRoute =
  ApiPublicHooksImportServicesRouteImport.update({
    id: '/api/public/hooks/import-services',
    path: '/api/public/hooks/import-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCleanLogsRoute = ApiPublicHooksCleanLogsRouteImport.update({
  id: '/api/public/hooks/clean-logs',
  path: '/api/public/hooks/clean-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksBalanceSyncRoute =
  ApiPublicHooksBalanceSyncRouteImport.update({
    id: '/api/public/hooks/balance-sync',
    path: '/api/public/hooks/balance-sync',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/dashboard/add-funds': typeof AuthenticatedDashboardAddFundsRoute
  '/dashboard/order-history': typeof AuthenticatedDashboardOrderHistoryRoute
  '/dashboard/refill': typeof AuthenticatedDashboardRefillRoute
  '/dashboard/transactions': typeof AuthenticatedDashboardTransactionsRoute
  '/api/public/ping': typeof ApiPublicPingRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/api/public/hooks/balance-sync': typeof ApiPublicHooksBalanceSyncRoute
  '/api/public/hooks/clean-logs': typeof ApiPublicHooksCleanLogsRoute
  '/api/public/hooks/import-services': typeof ApiPublicHooksImportServicesRoute
  '/api/public/hooks/retry-failed-orders': typeof ApiPublicHooksRetryFailedOrdersRoute
  '/api/public/hooks/status-sync': typeof ApiPublicHooksStatusSyncRoute
  '/api/public/hooks/telegram': typeof ApiPublicHooksTelegramRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/dashboard/add-funds': typeof AuthenticatedDashboardAddFundsRoute
  '/dashboard/order-history': typeof AuthenticatedDashboardOrderHistoryRoute
  '/dashboard/refill': typeof AuthenticatedDashboardRefillRoute
  '/dashboard/transactions': typeof AuthenticatedDashboardTransactionsRoute
  '/api/public/ping': typeof ApiPublicPingRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/api/public/hooks/balance-sync': typeof ApiPublicHooksBalanceSyncRoute
  '/api/public/hooks/clean-logs': typeof ApiPublicHooksCleanLogsRoute
  '/api/public/hooks/import-services': typeof ApiPublicHooksImportServicesRoute
  '/api/public/hooks/retry-failed-orders': typeof ApiPublicHooksRetryFailedOrdersRoute
  '/api/public/hooks/status-sync': typeof ApiPublicHooksStatusSyncRoute
  '/api/public/hooks/telegram': typeof ApiPublicHooksTelegramRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/dashboard/add-funds': typeof AuthenticatedDashboardAddFundsRoute
  '/_authenticated/dashboard/order-history': typeof AuthenticatedDashboardOrderHistoryRoute
  '/_authenticated/dashboard/refill': typeof AuthenticatedDashboardRefillRoute
  '/_authenticated/dashboard/transactions': typeof AuthenticatedDashboardTransactionsRoute
  '/api/public/ping': typeof ApiPublicPingRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/api/public/hooks/balance-sync': typeof ApiPublicHooksBalanceSyncRoute
  '/api/public/hooks/clean-logs': typeof ApiPublicHooksCleanLogsRoute
  '/api/public/hooks/import-services': typeof ApiPublicHooksImportServicesRoute
  '/api/public/hooks/retry-failed-orders': typeof ApiPublicHooksRetryFailedOrdersRoute
  '/api/public/hooks/status-sync': typeof ApiPublicHooksStatusSyncRoute
  '/api/public/hooks/telegram': typeof ApiPublicHooksTelegramRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/admin/logs'
    | '/admin/orders'
    | '/admin/providers'
    | '/admin/services'
    | '/dashboard/add-funds'
    | '/dashboard/order-history'
    | '/dashboard/refill'
    | '/dashboard/transactions'
    | '/api/public/ping'
    | '/admin/'
    | '/dashboard/'
    | '/api/public/hooks/balance-sync'
    | '/api/public/hooks/clean-logs'
    | '/api/public/hooks/import-services'
    | '/api/public/hooks/retry-failed-orders'
    | '/api/public/hooks/status-sync'
    | '/api/public/hooks/telegram'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/logs'
    | '/admin/orders'
    | '/admin/providers'
    | '/admin/services'
    | '/dashboard/add-funds'
    | '/dashboard/order-history'
    | '/dashboard/refill'
    | '/dashboard/transactions'
    | '/api/public/ping'
    | '/admin'
    | '/dashboard'
    | '/api/public/hooks/balance-sync'
    | '/api/public/hooks/clean-logs'
    | '/api/public/hooks/import-services'
    | '/api/public/hooks/retry-failed-orders'
    | '/api/public/hooks/status-sync'
    | '/api/public/hooks/telegram'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/providers'
    | '/_authenticated/admin/services'
    | '/_authenticated/dashboard/add-funds'
    | '/_authenticated/dashboard/order-history'
    | '/_authenticated/dashboard/refill'
    | '/_authenticated/dashboard/transactions'
    | '/api/public/ping'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
    | '/api/public/hooks/balance-sync'
    | '/api/public/hooks/clean-logs'
    | '/api/public/hooks/import-services'
    | '/api/public/hooks/retry-failed-orders'
    | '/api/public/hooks/status-sync'
    | '/api/public/hooks/telegram'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiPublicPingRoute: typeof ApiPublicPingRoute
  ApiPublicHooksBalanceSyncRoute: typeof ApiPublicHooksBalanceSyncRoute
  ApiPublicHooksCleanLogsRoute: typeof ApiPublicHooksCleanLogsRoute
  ApiPublicHooksImportServicesRoute: typeof ApiPublicHooksImportServicesRoute
  ApiPublicHooksRetryFailedOrdersRoute: typeof ApiPublicHooksRetryFailedOrdersRoute
  ApiPublicHooksStatusSyncRoute: typeof ApiPublicHooksStatusSyncRoute
  ApiPublicHooksTelegramRoute: typeof ApiPublicHooksTelegramRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/ping': {
      id: '/api/public/ping'
      path: '/api/public/ping'
      fullPath: '/api/public/ping'
      preLoaderRoute: typeof ApiPublicPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/transactions': {
      id: '/_authenticated/dashboard/transactions'
      path: '/dashboard/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof AuthenticatedDashboardTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/refill': {
      id: '/_authenticated/dashboard/refill'
      path: '/dashboard/refill'
      fullPath: '/dashboard/refill'
      preLoaderRoute: typeof AuthenticatedDashboardRefillRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/order-history': {
      id: '/_authenticated/dashboard/order-history'
      path: '/dashboard/order-history'
      fullPath: '/dashboard/order-history'
      preLoaderRoute: typeof AuthenticatedDashboardOrderHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/add-funds': {
      id: '/_authenticated/dashboard/add-funds'
      path: '/dashboard/add-funds'
      fullPath: '/dashboard/add-funds'
      preLoaderRoute: typeof AuthenticatedDashboardAddFundsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/providers': {
      id: '/_authenticated/admin/providers'
      path: '/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AuthenticatedAdminProvidersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/hooks/telegram': {
      id: '/api/public/hooks/telegram'
      path: '/api/public/hooks/telegram'
      fullPath: '/api/public/hooks/telegram'
      preLoaderRoute: typeof ApiPublicHooksTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/status-sync': {
      id: '/api/public/hooks/status-sync'
      path: '/api/public/hooks/status-sync'
      fullPath: '/api/public/hooks/status-sync'
      preLoaderRoute: typeof ApiPublicHooksStatusSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/retry-failed-orders': {
      id: '/api/public/hooks/retry-failed-orders'
      path: '/api/public/hooks/retry-failed-orders'
      fullPath: '/api/public/hooks/retry-failed-orders'
      preLoaderRoute: typeof ApiPublicHooksRetryFailedOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/import-services': {
      id: '/api/public/hooks/import-services'
      path: '/api/public/hooks/import-services'
      fullPath: '/api/public/hooks/import-services'
      preLoaderRoute: typeof ApiPublicHooksImportServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/clean-logs': {
      id: '/api/public/hooks/clean-logs'
      path: '/api/public/hooks/clean-logs'
      fullPath: '/api/public/hooks/clean-logs'
      preLoaderRoute: typeof ApiPublicHooksCleanLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/balance-sync': {
      id: '/api/public/hooks/balance-sync'
      path: '/api/public/hooks/balance-sync'
      fullPath: '/api/public/hooks/balance-sync'
      preLoaderRoute: typeof ApiPublicHooksBalanceSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminProvidersRoute: typeof AuthenticatedAdminProvidersRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
    AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
    AuthenticatedAdminProvidersRoute: AuthenticatedAdminProvidersRoute,
    AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDashboardAddFundsRoute: typeof AuthenticatedDashboardAddFundsRoute
  AuthenticatedDashboardOrderHistoryRoute: typeof AuthenticatedDashboardOrderHistoryRoute
  AuthenticatedDashboardRefillRoute: typeof AuthenticatedDashboardRefillRoute
  AuthenticatedDashboardTransactionsRoute: typeof AuthenticatedDashboardTransactionsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDashboardAddFundsRoute: AuthenticatedDashboardAddFundsRoute,
  AuthenticatedDashboardOrderHistoryRoute:
    AuthenticatedDashboardOrderHistoryRoute,
  AuthenticatedDashboardRefillRoute: AuthenticatedDashboardRefillRoute,
  AuthenticatedDashboardTransactionsRoute:
    AuthenticatedDashboardTransactionsRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiPublicPingRoute: ApiPublicPingRoute,
  ApiPublicHooksBalanceSyncRoute: ApiPublicHooksBalanceSyncRoute,
  ApiPublicHooksCleanLogsRoute: ApiPublicHooksCleanLogsRoute,
  ApiPublicHooksImportServicesRoute: ApiPublicHooksImportServicesRoute,
  ApiPublicHooksRetryFailedOrdersRoute: ApiPublicHooksRetryFailedOrdersRoute,
  ApiPublicHooksStatusSyncRoute: ApiPublicHooksStatusSyncRoute,
  ApiPublicHooksTelegramRoute: ApiPublicHooksTelegramRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
